-- Complete Supabase schema for the study room app.
-- Run in Supabase SQL Editor for a fresh project before using the app.

create extension if not exists pgcrypto;

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  last_checkin_date date,
  consecutive_days integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists study_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  duration_minutes integer not null check (duration_minutes > 0),
  subject text not null default '未分类',
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  task_date date not null,
  text text not null,
  done boolean not null default false,
  duration_minutes integer not null default 0,
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high')),
  parent_id bigint references tasks(id) on delete cascade,
  subtask_count integer not null default 0,
  completed_subtask_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists daily_reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  review_date date not null,
  content text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, review_date)
);

create table if not exists timer_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  started_at timestamptz not null,
  duration integer not null,
  remaining integer not null,
  timer_mode text not null,
  is_free_mode boolean not null default false,
  elapsed_in_free_mode integer not null default 0,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists task_time_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  task_id bigint not null references tasks(id) on delete cascade,
  task_date date not null,
  duration_minutes integer not null check (duration_minutes > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (task_id)
);

create index if not exists idx_profiles_last_checkin_date on profiles(last_checkin_date);
create index if not exists idx_study_sessions_user_id on study_sessions(user_id);
create index if not exists idx_study_sessions_created_at on study_sessions(created_at desc);
create index if not exists idx_study_sessions_ended_at on study_sessions(ended_at desc);
create index if not exists idx_study_sessions_subject on study_sessions(subject);
create index if not exists idx_tasks_user_date on tasks(user_id, task_date);
create index if not exists idx_tasks_parent_id on tasks(parent_id);
create index if not exists idx_daily_reviews_user_date on daily_reviews(user_id, review_date);
create index if not exists idx_timer_sessions_user_id on timer_sessions(user_id);
create index if not exists idx_timer_sessions_updated_at on timer_sessions(updated_at desc);
create index if not exists idx_task_time_entries_user_id on task_time_entries(user_id);
create index if not exists idx_task_time_entries_task_date on task_time_entries(task_date);
create index if not exists idx_task_time_entries_task_id on task_time_entries(task_id);

alter table profiles enable row level security;
alter table study_sessions enable row level security;
alter table tasks enable row level security;
alter table daily_reviews enable row level security;
alter table timer_sessions enable row level security;
alter table task_time_entries enable row level security;

drop policy if exists "Users can view own profile" on profiles;
create policy "Users can view own profile"
  on profiles for select
  using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on profiles;
create policy "Users can insert own profile"
  on profiles for insert
  with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on profiles;
create policy "Users can update own profile"
  on profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Users can view own study sessions" on study_sessions;
create policy "Users can view own study sessions"
  on study_sessions for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own study sessions" on study_sessions;
create policy "Users can insert own study sessions"
  on study_sessions for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own study sessions" on study_sessions;
create policy "Users can update own study sessions"
  on study_sessions for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own study sessions" on study_sessions;
create policy "Users can delete own study sessions"
  on study_sessions for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can view own tasks" on tasks;
create policy "Users can view own tasks"
  on tasks for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own tasks" on tasks;
create policy "Users can insert own tasks"
  on tasks for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own tasks" on tasks;
create policy "Users can update own tasks"
  on tasks for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own tasks" on tasks;
create policy "Users can delete own tasks"
  on tasks for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can view own daily reviews" on daily_reviews;
create policy "Users can view own daily reviews"
  on daily_reviews for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own daily reviews" on daily_reviews;
create policy "Users can insert own daily reviews"
  on daily_reviews for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own daily reviews" on daily_reviews;
create policy "Users can update own daily reviews"
  on daily_reviews for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own daily reviews" on daily_reviews;
create policy "Users can delete own daily reviews"
  on daily_reviews for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can view own timer sessions" on timer_sessions;
create policy "Users can view own timer sessions"
  on timer_sessions for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own timer sessions" on timer_sessions;
create policy "Users can insert own timer sessions"
  on timer_sessions for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own timer sessions" on timer_sessions;
create policy "Users can update own timer sessions"
  on timer_sessions for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own timer sessions" on timer_sessions;
create policy "Users can delete own timer sessions"
  on timer_sessions for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can view own task time entries" on task_time_entries;
create policy "Users can view own task time entries"
  on task_time_entries for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own task time entries" on task_time_entries;
create policy "Users can insert own task time entries"
  on task_time_entries for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own task time entries" on task_time_entries;
create policy "Users can update own task time entries"
  on task_time_entries for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own task time entries" on task_time_entries;
create policy "Users can delete own task time entries"
  on task_time_entries for delete
  using (auth.uid() = user_id);

grant select, insert, update, delete on task_time_entries to authenticated;

create or replace view study_activity_entries as
select
  ('session-' || s.id::text) as activity_id,
  s.user_id,
  s.duration_minutes,
  coalesce(s.subject, '未分类') as subject,
  s.ended_at as activity_at,
  s.created_at,
  'session'::text as activity_type,
  null::bigint as task_id,
  null::date as activity_date
from study_sessions s
union all
select
  ('task-' || t.id::text) as activity_id,
  t.user_id,
  t.duration_minutes,
  '任务补记'::text as subject,
  (t.task_date::timestamp at time zone 'Asia/Shanghai') as activity_at,
  t.created_at,
  'task'::text as activity_type,
  t.task_id,
  t.task_date as activity_date
from task_time_entries t;

create or replace function public.get_user_subject_breakdown(
  target_user_id uuid,
  rank_type text default 'daily'
)
returns table (
  subject text,
  minutes integer,
  percent numeric
)
language sql
security definer
set search_path = public
as $$
  with filtered_sessions as (
    select
      coalesce(a.subject, '未分类') as subject,
      a.duration_minutes
    from study_activity_entries a
    where a.user_id = target_user_id
      and (
        rank_type <> 'daily'
        or (
          a.activity_at >= date_trunc('day', now() at time zone 'Asia/Shanghai') at time zone 'Asia/Shanghai'
          and a.activity_at < (date_trunc('day', now() at time zone 'Asia/Shanghai') + interval '1 day') at time zone 'Asia/Shanghai'
        )
      )
  ),
  subject_totals as (
    select
      fs.subject,
      sum(fs.duration_minutes)::integer as minutes
    from filtered_sessions fs
    group by fs.subject
  ),
  overall as (
    select coalesce(sum(st.minutes), 0) as total_minutes
    from subject_totals st
  )
  select
    st.subject,
    st.minutes,
    case
      when o.total_minutes > 0 then round((st.minutes::numeric / o.total_minutes::numeric) * 100, 2)
      else 0
    end as percent
  from subject_totals st
  cross join overall o
  order by st.minutes desc, st.subject asc;
$$;

revoke all on function public.get_user_subject_breakdown(uuid, text) from public;
grant execute on function public.get_user_subject_breakdown(uuid, text) to authenticated;

create or replace view subject_breakdown as
with subject_totals as (
  select
    a.user_id,
    coalesce(a.subject, '未分类') as subject,
    sum(a.duration_minutes)::integer as minutes
  from study_activity_entries a
  group by a.user_id, coalesce(a.subject, '未分类')
),
user_totals as (
  select
    st.user_id,
    sum(st.minutes)::integer as total_minutes
  from subject_totals st
  group by st.user_id
)
select
  st.user_id,
  st.subject,
  st.minutes,
  case
    when ut.total_minutes > 0 then round((st.minutes::numeric / ut.total_minutes::numeric) * 100, 2)
    else 0
  end as percent
from subject_totals st
join user_totals ut on ut.user_id = st.user_id;

create or replace view daily_subject_breakdown as
with subject_totals as (
  select
    a.user_id,
    coalesce(a.subject, '未分类') as subject,
    sum(a.duration_minutes)::integer as minutes
  from study_activity_entries a
  where a.activity_at >= date_trunc('day', now() at time zone 'Asia/Shanghai') at time zone 'Asia/Shanghai'
    and a.activity_at < (date_trunc('day', now() at time zone 'Asia/Shanghai') + interval '1 day') at time zone 'Asia/Shanghai'
  group by a.user_id, coalesce(a.subject, '未分类')
),
user_totals as (
  select
    st.user_id,
    sum(st.minutes)::integer as total_minutes
  from subject_totals st
  group by st.user_id
)
select
  st.user_id,
  st.subject,
  st.minutes,
  case
    when ut.total_minutes > 0 then round((st.minutes::numeric / ut.total_minutes::numeric) * 100, 2)
    else 0
  end as percent
from subject_totals st
join user_totals ut on ut.user_id = st.user_id;

create or replace view leaderboard as
select
  p.id as user_id,
  coalesce(p.username, split_part(u.email, '@', 1), '学习者') as username,
  coalesce(sum(a.duration_minutes), 0)::integer as total_minutes,
  count(a.activity_id)::integer as session_count
from profiles p
join auth.users u on u.id = p.id
left join study_activity_entries a on a.user_id = p.id
group by p.id, p.username, u.email
order by total_minutes desc;

create or replace view daily_leaderboard as
select
  p.id as user_id,
  coalesce(p.username, split_part(u.email, '@', 1), '学习者') as username,
  coalesce(sum(a.duration_minutes), 0)::integer as total_minutes,
  count(a.activity_id)::integer as session_count
from profiles p
join auth.users u on u.id = p.id
left join study_activity_entries a
  on a.user_id = p.id
  and a.activity_at >= date_trunc('day', now() at time zone 'Asia/Shanghai') at time zone 'Asia/Shanghai'
  and a.activity_at < (date_trunc('day', now() at time zone 'Asia/Shanghai') + interval '1 day') at time zone 'Asia/Shanghai'
group by p.id, p.username, u.email
order by total_minutes desc;

grant select on leaderboard to authenticated;
grant select on daily_leaderboard to authenticated;
grant select on subject_breakdown to authenticated;
grant select on daily_subject_breakdown to authenticated;
grant select on study_activity_entries to authenticated;
